### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Somnus-CYN** [Tencent/PatrickStar#230]
我在尝试用你们提供的样例中的train_simple_net.py运行时，有一个报错：
Traceback (most recent call last):
  File "/home/somnus/Learn_deeplearing/PatrickStar-master/examples/train_simple_net.py", line 90, in <module>
    model, optim = initialize_engine(model_func=model_func, local_rank=0, config=config)
  File "/home/somnus/Learn_deeplearing/PatrickStar-master/patrickstar/runtime/__init__.py", line 70, in initialize_engine
    client = PatrickStarClient(
  File "/home/somnus/Learn_deeplearing/PatrickStar-master/patrickstar/core/client.py", line 53, in __init__
    tracer_config = config.get("mem_tracer", None)
AttributeError: 'NoneType' object has no attribute 'get'
我并没有对代码进行任何改动，请问这是什么原因呢？

**Comment by zhuzilin** [comment]
抱歉，这是因为最近在抽离 mem_tracer 组件的时候没有设置好默认参数。已经在 develop branch 修复了，您可以 checkout 到 develop branch 试一下~
